// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYfsj0stUjPrY4yTjSvwzVg0eWq4HkGtE',
    appId: '1:705793250197:web:7d0f9b8e94d76e14385c9c',
    messagingSenderId: '705793250197',
    projectId: 'themimictrial',
    authDomain: 'themimictrial.firebaseapp.com',
    storageBucket: 'themimictrial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABFEx7UYCPYBFmKcHPwJ09I7ZKRERalU',
    appId: '1:705793250197:android:83744ea4c57018be385c9c',
    messagingSenderId: '705793250197',
    projectId: 'themimictrial',
    storageBucket: 'themimictrial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDO8iWXRsfvld7BEyK-vMPZ2uLQ9Id3a8',
    appId: '1:705793250197:ios:7b770f2723371c8d385c9c',
    messagingSenderId: '705793250197',
    projectId: 'themimictrial',
    storageBucket: 'themimictrial.appspot.com',
    iosClientId: '705793250197-mp8mmobuu9sv618gtnkq3q86qucvm0k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.themimictrial',
  );
}
